Backup/LCSK.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LCSK.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var cfg = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration(@"/");
            ViewBag.notinstalled = cfg.ConnectionStrings.ConnectionStrings["LCSK"] != null;
            return View();
        }

		public ActionResult TestingReferrer()
		{
			return View();
		}

    }
}

Backup/LCSK.Web/Controllers/InstallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using LCSK.Services;

namespace LCSK.Web.Controllers
{
    public class InstallController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string server, string dbname, string username, string password, string adminPassword)
        {
            if (!IsDatabaseCreated)
            {
                var cfg = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration(@"/");
                cfg.ConnectionStrings.ConnectionStrings.Add(new ConnectionStringSettings("LCSK",
                    string.Format("Data Source={0};Initial Catalog={1};{2}", server, dbname,
                        (!string.IsNullOrEmpty(username) && !string.IsNullOrEmpty(password) ? "User id:" + username + ";password: " + password : "Integrated Security=True;")
                    ), "System.Data.SqlClient"));

                cfg.Save();
            }

            return RedirectToAction("InstallDatabase", new { id = adminPassword });
        }

        public ActionResult InstallDatabase(string id)
        {
            if (OperatorService.CreateDatabase(id))
            {
                return RedirectToAction("InstallCompleted");
            }
            return RedirectToAction("InstallError");
        }

        public ActionResult InstallCompleted()
        {
            return View();
        }
    }
}

Backup/LCSK.Web/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Index</title>

	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
</head>
<body>
@if (ViewBag.notinstalled != null && (bool)ViewBag.notinstalled == false)
{
    <div style="border: 1px solid red;padding: 15px;font-size: 16px;color: Red;">
        The database is not installed.<br /><br />
        Please @Html.ActionLink("click here to start the installation", "Index", "Install")
    </div>
}
    <div>
        <h1>Demo page for chat button & Invitation line</h1>

		<a href="/livechat/session" target="_blank">
			<img id="lcsk_chatbutton" src="" alt="Chat button" />
		</a>
		<script type="text/javascript">
			document.getElementById('lcsk_chatbutton').src = '/livechat/chatimage?r=' + document.referrer;
		</script>
    </div>

	<h4><a href="/Home/TestingReferrer">Testing Referrer</a></h4>

	<div id="lcsk_invitation" style="display: none;">
	  <div style="position: absolute; width: 100%; height: 100%; z-index: 10002; background-color: black;
		filter: alpha(opacity=70); opacity: 0.7;top: 0px;left: 0px">
		&nbsp;
	  </div>
	  <table style="position: absolute; width: 100%; height: 100%; z-index: 10003;top: 0px;left: 0px;">
		<tr>
		  <td align="center" valign="middle">
			<div style="color: Black; font-weight: bolder; background-color: White; padding: 15px;
			  width: 300px;">
				<a href="/livechat/session/accept" class="lcsk_inviteActions" target="_blank">
					<img src="/content/lcsk/invitation.jpg" alt="An operator invited you to chat" />
				</a><br /><br />
				<a href="/livechat/session/accept" class="lcsk_inviteActions" target="_blank">Start the chat session</a> | 
				<a href="/livechat/session/reject" class="lcsk_inviteActions" target="_blank">No thank you!</a>
			</div>
		  </td>
		</tr>
	  </table>
	</div>
	<script src="/livechat/checkinviration" type="text/javascript"></script>

</body>
</html>

Backup/LCSK.Web/Views/Home/TestingReferrer.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Testing Referrer</title>

	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
</head>
<body>
    <div>
        <h1>Testing Referrer</h1>

		<a href="/livechat/session" target="_blank">
			<img id="lcsk_chatbutton" src="" alt="Chat button" />
		</a>
		<script type="text/javascript">
			document.getElementById('lcsk_chatbutton').src = '/livechat/chatimage?r=' + document.referrer;
		</script>
    </div>

	<div id="lcsk_invitation" style="display: none;">
	  <div style="position: absolute; width: 100%; height: 100%; z-index: 10002; background-color: black;
		filter: alpha(opacity=70); opacity: 0.7;top: 0px;left: 0px">
		&nbsp;
	  </div>
	  <table style="position: absolute; width: 100%; height: 100%; z-index: 10003;top: 0px;left: 0px;">
		<tr>
		  <td align="center" valign="middle">
			<div style="color: Black; font-weight: bolder; background-color: White; padding: 15px;
			  width: 300px;">
				<a href="/livechat/session/accept" class="lcsk_inviteActions" target="_blank">
					<img src="/content/lcsk/invitation.jpg" alt="An operator invited you to chat" />
				</a><br /><br />
				<a href="/livechat/session/accept" class="lcsk_inviteActions" target="_blank">Start the chat session</a> | 
				<a href="/livechat/session/reject" class="lcsk_inviteActions" target="_blank">No thank you!</a>
			</div>
		  </td>
		</tr>
	  </table>
	</div>
	<script src="/livechat/checkinviration" type="text/javascript"></script>

</body>
</html>